### Code written by Lucas Levrouw (2026)
### This script generates figure 2 of https://arxiv.org/abs/2512.22099
### If using this code, please cite the above paper.



# Run calculate-profiles.jl first to generate the data

using Revise
using VortexMass; const PROJECT_ROOT = pkgdir(VortexMass)
using DelimitedFiles
using NumericalIntegration

# Create necessary directories
mkpath("$PROJECT_ROOT/JLTP2026/tables/")
mkpath("$PROJECT_ROOT/JLTP2026/figures/")

read_from_table = false  # set to true to read masses from saved tables

zeta_crit_data = readdlm(normpath(joinpath(PROJECT_ROOT, "JLTP2026/critical_ζ.dat")), '\t')
zeta_crit_interactions = zeta_crit_data[:,1]
zeta_crit_vals = zeta_crit_data[:,2]


interactions = -1.0:0.1:2.0
rel_zetaVals = [0.0, 0.7, 0.9]
zetaCrit = zeros(length(interactions))

bc = "neumann"

L_kF = 150

if !read_from_table
    r_array  = Array{Union{Vector{Union{Float64, Missing}}, Missing}}(missing, length(interactions), length(rel_zetaVals))
    relaxed_profiles  = Array{Union{Vector{Union{Float64, Missing}}, Missing}}(missing, length(interactions), length(rel_zetaVals))

    i = 1

    for j in eachindex(interactions), k in eachindex(rel_zetaVals)
        int = interactions[j]
        T = 0.0
        β = 1000

        index_zetacrit = findfirst(int .== zeta_crit_interactions)

        if index_zetacrit === nothing
            println("No ζ_c data for int = $int, skipping...")
            continue
        end
        zeta_crit = zeta_crit_vals[index_zetacrit]

        zetaCrit[j] = zeta_crit

        ζ = rel_zetaVals[k] * zeta_crit

        (; Δ, μ, A_itp, Dt_itp, Ct, Et, Q, Rt, G, ξ2) = calculate_mf_eft_parameters(β, int, ζ)

        relaxed_data = readdlm(normpath(joinpath(PROJECT_ROOT,"data/relaxed_profile_$(bc)_int=$(int)_T=$(T)Tc_ζ=$(rel_zetaVals[k])ζc.csv")),',')

        r_array[j,k] = relaxed_data[:,1]
        relaxed_profiles[j,k] = relaxed_data[:,2]
    end

    associated_masses = zeros(length(interactions), length(rel_zetaVals))
    internal_masses = copy(associated_masses)
    healing_lengths = copy(associated_masses)
    correction_factor_a = copy(associated_masses)
    correction_factor_i = copy(associated_masses)

    i = 1

    for j in eachindex(interactions), k in eachindex(rel_zetaVals)

        int = interactions[j]
        T = 0.0
        β = 1000
        ζ = zetaCrit[j] * rel_zetaVals[k]
        (; Δ, μ, A_itp, Dt_itp, Ct, Et, Q, Rt, G, ξ2) = calculate_mf_eft_parameters(β, int, ζ)
        u = Δ*relaxed_profiles[j,k]

        healing_lengths[j,k] = ξ2
        local L = L_kF/ξ2

        r = r_array[j,k]

        ρ_tot = 1/2*broadcast(Φ->numberDensity_mf(β, μ, ζ, Φ)[1],u)
        ρ_s = @. 2*Ct*u^2
        ρ_n = ρ_tot - ρ_s

        ρ_∞ = 1/6π^2
        ρ_s_∞ = 2*Ct*Δ^2
        ρ_n_∞ = ρ_∞ - ρ_s_∞

        δρ_n_∞ = -Δ^2 * Dt_int(β, μ, ζ, Δ)[1] + ρ_s_∞

        Δρ_∞ = 1/2 * imbalanceDensity_mf(β, μ, ζ, Δ)[1]

        idx = findfirst(x->x≥L*ξ2, r)

        m_a = 2π * integrate(r[1:idx], (r.*(ρ_s_∞  .-ρ_s))[1:idx])
        m_i = 2π * integrate(r[1:idx], (r.*(ρ_n .- ρ_n_∞))[1:idx])

        associated_masses[j,k] = m_a
        internal_masses[j,k] = m_i

        m_a0 = 2π * integrate(r, (r.*(ρ_s_∞  .-ρ_s))) + π*ξ2^2 * ρ_s_∞*log(ξ2/r[end])
        m_i0 = 2π * integrate(r, (r.*(ρ_n .- ρ_n_∞))) + π*ξ2^2 * δρ_n_∞ *log(ξ2/r[end])

        correction_factor_a[j,k] = exp(-m_a0/(π*ξ2^2 * ρ_s_∞))
        correction_factor_i[j,k] = exp(-m_i0/(π*ξ2^2 * δρ_n_∞ ))

        if max(ρ_n_∞, Δρ_∞) > 1e-8
            println("int = $(interactions[j]), ζ =$(rel_zetaVals[k])ζc")
            println("ρ_n_∞ = $(ρ_n_∞),  Δρ_∞ = $(Δρ_∞)")
            @show m_a, m_i
            @show ξ2
        end
    end

    total_masses = associated_masses .+ internal_masses

    open("$PROJECT_ROOT/JLTP2026/tables/vortex_masses_T=0.csv", "w") do io
        write(io, "# Vortex masses at T=0 as a function of interaction strength and imbalance\n")
        write(io, "# Generated by JLTP2026/calculate-and-plot-vortex-masses.jl\n")
        write(io, "# Columns: (k_F a_s)^(-1), zeta/zeta_c, M_a/(m k_F), M_i/(m k_F), alpha_a, alpha_i, xi2*(k_F)\n")
        for k in eachindex(rel_zetaVals), j in eachindex(interactions)
            writedlm(io, [interactions[j] rel_zetaVals[k] 2*associated_masses[j,k] 2*internal_masses[j,k] correction_factor_a[j,k] correction_factor_i[j,k] healing_lengths[j,k]], ',')
        end
    end
else
    data = readdlm("$PROJECT_ROOT/JLTP2026/tables/vortex_masses_T=0.csv", ',', comments=true)
    ni, nz = length(interactions), length(rel_zetaVals)
    associated_masses   = reshape(data[:, 3], ni, nz) ./ 2
    internal_masses     = reshape(data[:, 4], ni, nz) ./ 2
    correction_factor_a = reshape(data[:, 5], ni, nz)
    correction_factor_i = reshape(data[:, 6], ni, nz)
    healing_lengths     = reshape(data[:, 7], ni, nz)
    total_masses        = associated_masses .+ internal_masses
end




## Create plots and tables

include("initialize_makie.jl")
light_mass_colors = ColorSchemes.tab20[2:2:6]




markers1 = [:rect, :utriangle, :cross]
markers2 = [:diamond, :dtriangle, :xcross]

fig = Figure(size = (490pt,210pt), figure_padding = (0,2,3,0)) # left, right, bottom, top
ax1 = Axis(fig[1:2, 1], xlabel = L"(k_Fa_s)^{-1}", ylabel = L"\frac{M_{tot}}{m\, k_F}", yscale = log10, width = 180pt, limits = (-1.05,2.05,nothing,10^1.5))
ax1.xticks = -2:1:3

for k in eachindex(rel_zetaVals)
    scatter!(ax1, interactions, 2*total_masses[:, k], marker = markers1[k],
    color = mass_colors[k], label=latexstring("ζ/ζ_c = $(rel_zetaVals[k])"))
end
axislegend(ax1, rowgap = 0)



ax3 = Axis(fig[1:2, 2], xlabel = L"(k_Fa_s)^{-1}", ylabel = L"\alpha", limits = (-1.05,2.05,nothing,nothing))
ax3.xticks = -2:1:3
ax3.yticks = 0.0:0.2:0.8

for k in eachindex(rel_zetaVals)

scatter!(ax3, interactions, correction_factor_a[:,k], color = mass_colors[k], marker=markers1[k], label = L"\alpha_a(ζ/ζ_c = %$(rel_zetaVals[k]))")
scatter!(ax3, interactions, correction_factor_i[:,k], color = light_mass_colors[k], marker = markers2[k], label = L"\alpha_i(ζ/ζ_c = %$(rel_zetaVals[k]))")

end

lines!(ax3, [(-2,exp(-3/4)),(3,exp(-3/4))], color = :gray, linestyle = :dot)
Legend(fig[1:2,3], ax3, tellheight = true)


rowgap!(fig.layout, 10)

Label(fig[1,1:2,TopLeft()], "(a)", halign =:left)
Label(fig[1,2,TopLeft()], "(b)", halign=:left)

save("$(PROJECT_ROOT)/JLTP2026/figures/fig2_vortex_mass_T=0.pdf", fig)

println("Done")