### Code written by Lucas Levrouw (2026)
### This script generates figure 3 of https://arxiv.org/abs/2512.22099
### If using this code, please cite the above paper.



# Run calculate-profiles.jl first to generate the data

using Revise
using VortexMass; const PROJECT_ROOT = pkgdir(VortexMass)
using DelimitedFiles
using NumericalIntegration

# Create necessary directories
mkpath("$PROJECT_ROOT/JLTP2026/tables/")
mkpath("$PROJECT_ROOT/JLTP2026/figures/")

read_from_table = false  # set to true to read masses from saved tables

zeta_crit_data = readdlm(normpath(joinpath(PROJECT_ROOT, "JLTP2026/critical_ζ.dat")), '\t')
zeta_crit_interactions = zeta_crit_data[:,1]
zeta_crit_vals = zeta_crit_data[:,2]


temperatures = [0.0, 0.5, 0.9]
interactions = [-1.0, 0.0, 1.0]
rel_zetaVals = 0.0:0.05:0.95
zetaCrit = zeros(length(interactions))

bc = "neumann"

L_kF = 150

if !read_from_table
    r_array  = Array{Union{Vector{Union{Float64, Missing}}, Missing}}(missing, length(interactions), length(rel_zetaVals))
    relaxed_profiles  = Array{Union{Vector{Union{Float64, Missing}}, Missing}}(missing, length(interactions), length(rel_zetaVals))

    i = 1  # T=0

    for j in eachindex(interactions), k in eachindex(rel_zetaVals)
        int = interactions[j]
        T = temperatures[i]
        β = (T == 0) ? 1000 : 1/(T*find_Tc(int))

        index_zetacrit = findfirst(int .== zeta_crit_interactions)

        if index_zetacrit === nothing
            println("No ζ_c data for int = $int, skipping...")
            continue
        end
        zeta_crit = zeta_crit_vals[index_zetacrit]

        zetaCrit[j] = zeta_crit

        ζ = rel_zetaVals[k] * zeta_crit

        (; Δ, μ, A_itp, Dt_itp, Ct, Et, Q, Rt, G, ξ2) = calculate_mf_eft_parameters(β, int, ζ)

        relaxed_data = readdlm(normpath(joinpath(PROJECT_ROOT,"data/relaxed_profile_$(bc)_int=$(int)_T=$(T)Tc_ζ=$(rel_zetaVals[k])ζc.csv")),',')
        r_array[j,k] = relaxed_data[:,1]
        relaxed_profiles[j,k] = relaxed_data[:,2]
    end

    associated_masses = zeros(length(interactions), length(rel_zetaVals))
    internal_masses = copy(associated_masses)
    imbalance_masses = copy(associated_masses)

    healing_lengths = copy(associated_masses)
    correction_factor_a = copy(associated_masses)
    correction_factor_i = copy(associated_masses)

    i = 1  # T=0

    for j in eachindex(interactions), k in eachindex(rel_zetaVals)
        int = interactions[j]
        T = temperatures[i]
        Tc = find_Tc(int)
        β = (T == 0) ? 1000 : 1/(T*Tc)
        ζ = zetaCrit[j] * rel_zetaVals[k]
        (; Δ, μ, A_itp, Dt_itp, Ct, Et, Q, Rt, G, ξ2) = calculate_mf_eft_parameters(β, int, ζ)
        u = Δ*relaxed_profiles[j,k]

        healing_lengths[j,k] = ξ2
        local L = L_kF/ξ2

        r = r_array[j,k]

        ρ_tot = 1/2*broadcast(Φ->numberDensity_mf(β, μ, ζ, Φ)[1],u)
        ρ_s = @. 2*Ct*u^2
        ρ_n = ρ_tot - ρ_s
        ρ_imb = 1/2*broadcast(Φ->imbalanceDensity_mf(β, μ, ζ, Φ)[1],u)

        ρ_∞ = 1/6π^2
        ρ_s_∞ = 2*Ct*Δ^2
        ρ_n_∞ = ρ_∞ - ρ_s_∞
        ρ_imb_∞ = 1/2 * imbalanceDensity_mf(β, μ, ζ, Δ)[1]

        δρ_n_∞ = -Δ^2 * Dt_int(β, μ, ζ, Δ)[1] + ρ_s_∞

        idx = findfirst(x->x≥L*ξ2, r)

        m_a = 2π * integrate(r[1:idx], (r.*(ρ_s_∞  .-ρ_s))[1:idx])
        m_i = 2π * integrate(r[1:idx], (r.*(ρ_n .- ρ_n_∞))[1:idx])
        m_imb = 2π * integrate(r[1:idx], (r.*(ρ_imb .- ρ_imb_∞))[1:idx])

        associated_masses[j,k] = m_a
        internal_masses[j,k] = m_i
        imbalance_masses[j,k] = m_imb

        m_a0 = 2π * integrate(r, (r.*(ρ_s_∞  .-ρ_s))) + π*ξ2^2 * ρ_s_∞*log(ξ2/r[end])
        m_i0 = 2π * integrate(r, (r.*(ρ_n .- ρ_n_∞))) + π*ξ2^2 * δρ_n_∞ *log(ξ2/r[end])

        correction_factor_a[j,k] = exp(-m_a0/(π*ξ2^2 * ρ_s_∞))
        correction_factor_i[j,k] = exp(-m_i0/(π*ξ2^2 * δρ_n_∞ ))
    end

    total_masses = associated_masses .+ internal_masses

    open("$PROJECT_ROOT/JLTP2026/tables/vortex_masses_as_function_of_zeta.csv", "w") do io
        write(io, "# Vortex masses at T=0 as a function of imbalance, for selected interaction strengths\n")
        write(io, "# Generated by JLTP2026/calculate-and-plot-vortex-masses-as-a-function-of-zeta.jl\n")
        write(io, "# Columns: (k_F a_s)^(-1), zeta/zeta_c, M_a/(m k_F), M_i/(m k_F), M_imb/(m k_F), alpha_a, alpha_i\n")
        for k in eachindex(rel_zetaVals), j in eachindex(interactions)
            writedlm(io, [interactions[j] rel_zetaVals[k] 2*associated_masses[j,k] 2*internal_masses[j,k] 2*imbalance_masses[j,k] correction_factor_a[j,k] correction_factor_i[j,k]], ',')
        end
    end
else
    data = readdlm("$PROJECT_ROOT/JLTP2026/tables/vortex_masses_as_function_of_zeta.csv", ',', comments=true)
    ni, nz = length(interactions), length(rel_zetaVals)
    associated_masses   = reshape(data[:, 3], ni, nz) ./ 2
    internal_masses     = reshape(data[:, 4], ni, nz) ./ 2
    imbalance_masses    = reshape(data[:, 5], ni, nz) ./ 2
    correction_factor_a = reshape(data[:, 6], ni, nz)
    correction_factor_i = reshape(data[:, 7], ni, nz)
    total_masses        = associated_masses .+ internal_masses
end



## Create plots and tables

include("initialize_makie.jl")
light_mass_colors = ColorSchemes.tab20[2:2:6]



### Vortex mass as a function of ζ

fig = Figure(size = (490pt,196pt), figure_padding = (0.5pt,5pt,2pt,1.5pt))
axes = [Axis(fig[1, j], xlabel = L"\zeta/\zeta_c", ylabel = L"\frac{M}{M_{\text{tot}}(\zeta = 0)}", limits = ((-0.05,1.0),(nothing,nothing)), xticks = 0.0:0.2:1.0) for j in eachindex(interactions)] #width = 230pt)
linkaxes!(axes...)

hideydecorations!.(axes[2], grid=false)
hideydecorations!.(axes[3], grid=false)

markers1 = [:circle, :rect, :utriangle]
markers2 = [:star5, :diamond, :dtriangle]

for j in eachindex(interactions)
    scatter!(axes[j], rel_zetaVals, total_masses[j, :]./total_masses[j, begin], marker = markers1[1],
    color = mass_colors[1], label="total")
    scatter!(axes[j], rel_zetaVals, associated_masses[j, :]./total_masses[j, begin], marker = markers1[2],
    color = mass_colors[2], label="associated")
    scatter!(axes[j], rel_zetaVals, internal_masses[j, :]./total_masses[j, begin], marker = markers1[3],
    color = mass_colors[3], label="internal")
    scatter!(axes[j], rel_zetaVals, imbalance_masses[j, :]./total_masses[j, begin], marker = :star5,color = mass_colors[4], label="imbalance")

    Label(fig[1,j,Top()], L"(k_F a_s)^{-1} = %$(Int64(interactions[j]))", halign = :center, padding = (0,0,4,0))
end

Legend(fig[0,1:3], axes[1], orientation = :horizontal)

save("$(PROJECT_ROOT)/JLTP2026/figures/fig3_vortex_mass_as_a_function_of_zeta.pdf", fig)
